language: php

php:
    - 5.4

before_script:
    - composer self-update
    - composer install --prefer-source --dev --no-interaction

script: ./vendor/bin/phpspec run --format=pretty

notifications:
    email:
        - michaeleschbacher@gmail.com
